# Generated by Django 5.0.2 on 2024-02-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Telegram User', 'verbose_name_plural': 'Telegram Users'},
        ),
        migrations.AlterModelTable(
            name='telegramuser',
            table='telegram_user',
        ),
    ]
