# Generated by Django 5.0.2 on 2024-03-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_telegramuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
