# Generated by Django 5.0.2 on 2024-03-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_telegramuser_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
