# Generated by Django 5.0.2 on 2024-04-20 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_telegramuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='shipping_details',
        ),
    ]
