# Generated by Django 5.0.2 on 2024-04-20 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
        ('user', '0006_remove_telegramuser_shipping_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='shipping_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='shipping.shippingdetails'),
        ),
    ]
