# Generated by Django 5.0.2 on 2024-05-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_telegramuser_role_storeuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeuser',
            options={'verbose_name': 'Store User', 'verbose_name_plural': 'Store Users'},
        ),
        migrations.AlterModelTable(
            name='storeuser',
            table='store_user',
        ),
    ]
