# Generated by Django 5.0.2 on 2024-06-12 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_contactinformation_shippingaddress'),
        ('user', '0010_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='default_contact_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_contact_info', to='shipping.contactinformation'),
        ),
        migrations.AddField(
            model_name='storeuser',
            name='default_shipping_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_shipping_address', to='shipping.shippingaddress'),
        ),
    ]
