# Generated by Django 5.0.2 on 2026-06-13 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order_number', models.IntegerField(blank=True, unique=True)),
                ('fulfilment_status', models.CharField(choices=[('OPEN', 'open'), ('PENDING', 'pending'), ('UNFULFILLED', 'unfulfilled'), ('FULFILLED', 'fulfilled'), ('TRACKING', 'tracking'), ('CANCELLED', 'cancelled')], default='OPEN', max_length=20)),
                ('fulfilment_date', models.DateTimeField(blank=True, null=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cart.cart')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'orders',
                'ordering': ['-created'],
            },
        ),
    ]
