# Generated by Django 5.0.2 on 2024-02-17 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_total_price_remove_order_total_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.shippingdetails'),
        ),
    ]
