# Generated by Django 5.0.2 on 2024-04-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_payment_status_order_delivery_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetails',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
