# Generated by Django 5.0.2 on 2024-04-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_shippingdetails_shipping_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetails',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
