# Generated by Django 5.0.2 on 2024-04-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_shippingdetails_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetails',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10),
        ),
    ]
