# Generated by Django 5.0.2 on 2024-04-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_shippingdetails_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetails',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
