# Generated by Django 5.0.2 on 2024-04-20 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_shippingdetails_province_alter_shippingdetails_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_details',
        ),
    ]
