# Generated by Django 5.0.2 on 2024-04-20 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_order_shipping_details'),
        ('user', '0006_remove_telegramuser_shipping_details'),
        ('product', '0003_auto_20240411_0926')
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingDetails',
        ),
    ]
