# Generated by Django 5.0.2 on 2024-04-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_options_alter_order_cart_orderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='fulfilment_status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('FULFILLED', 'fulfilled'), ('CANCELLED', 'cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('PAID', 'paid'), ('REFUNDED', 'refunded'), ('EXPIRED', 'expired')], default='PENDING', max_length=20),
        ),
    ]
