# Generated by Django 5.0.2 on 2024-04-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_remove_order_order_status_order_fulfilment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_details',
        ),
        migrations.AlterField(
            model_name='order',
            name='fulfilment_status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('FULFILLED', 'fulfilled'), ('TRACKING', 'tracking'), ('CANCELLED', 'cancelled')], default='PENDING', max_length=20),
        ),
    ]
