# Generated by Django 5.0.2 on 2024-04-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_remove_order_shipping_details_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_order_variant',
        ),
    ]
