# Generated by Django 5.0.2 on 2024-04-24 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_remove_orderitem_unique_order_variant'),
        ('shipping', '0004_remove_shipping_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='shipping.shipping'),
        ),
    ]
