# Generated by Django 5.0.2 on 2024-04-24 12:20

from django.db import migrations


def add_shipping(apps, schema_editor):
    Shipping = apps.get_model("shipping", "Shipping")
    Order = apps.get_model("order", "Order")
    for order in Order.objects.all():
        if order.shipping is None:
            shipping = Shipping.objects.create()
            order.shipping = shipping
            order.save()
            shipping.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0018_order_shipping'),
    ]

    operations = [
        migrations.RunPython(
            add_shipping, reverse_func
        )
    ]
