# Generated by Django 5.0.2 on 2024-04-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20240424_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
