# Generated by Django 5.0.2 on 2024-04-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_remove_order_payment_status_delete_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subtotal_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='fulfilment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
