# Generated by Django 5.0.2 on 2024-04-28 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_user'),
        ('order', '0021_remove_order_delivery_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default='09f5154c-1757-4e3a-9990-79f7348a5b46', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cart.cart'),
            preserve_default=False,
        ),
    ]
