# Generated by Django 5.0.2 on 2024-04-29 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_user'),
        ('order', '0022_alter_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cart.cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fulfilment_status',
            field=models.CharField(choices=[('OPEN', 'open'), ('PENDING', 'pending'), ('UNFULFILLED', 'unfulfilled'), ('FULFILLED', 'fulfilled'), ('TRACKING', 'tracking'), ('CANCELLED', 'cancelled')], default='UNFULFILLED', max_length=20),
        ),
    ]
