# Generated by Django 5.0.2 on 2024-04-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_order_cart_alter_order_fulfilment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fulfilment_status',
            field=models.CharField(choices=[('OPEN', 'open'), ('PENDING', 'pending'), ('UNFULFILLED', 'unfulfilled'), ('FULFILLED', 'fulfilled'), ('TRACKING', 'tracking'), ('CANCELLED', 'cancelled')], default='OPEN', max_length=20),
        ),
    ]
