# Generated by Django 5.0.2 on 2024-05-20 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_order_fulfilment_status'),
        ('store', '0004_remove_store_owner_store_bot_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.store'),
        ),
    ]
