# Generated by Django 5.0.2 on 2026-06-13 12:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('store_name', models.TextField(max_length=100)),
                ('store_description', models.TextField(blank=True, max_length=255, null=True)),
                ('store_timezone', models.TextField(default='UTC', max_length=100)),
                ('is_connected_to_telegram', models.BooleanField(default=False)),
                ('store_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='StoreApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('store_name', models.TextField(max_length=100)),
                ('store_description', models.TextField(blank=True, max_length=255, null=True)),
                ('channels', models.TextField(blank=True, max_length=255, null=True)),
                ('product_category', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Store Application',
                'verbose_name_plural': 'Store Applications',
                'db_table': 'store_application',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='StoreBot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bot_username', models.TextField(blank=True, max_length=100, null=True)),
                ('token', models.TextField(blank=True, max_length=255, null=True)),
                ('telegram_store_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Store Bot',
                'verbose_name_plural': 'Store Bots',
                'db_table': 'store_bot',
            },
        ),
        migrations.CreateModel(
            name='StoreLogo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='store_logos')),
                ('logo_light', models.ImageField(blank=True, null=True, upload_to='store_logos')),
            ],
            options={
                'verbose_name': 'Store Logo',
                'verbose_name_plural': 'Store Logos',
                'db_table': 'store_logo',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='StoreSupportBot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bot_username', models.CharField(blank=True, max_length=100, null=True)),
                ('bot_token', models.CharField(blank=True, max_length=255, null=True)),
                ('group_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('message_thread_id', models.IntegerField(blank=True, null=True)),
                ('greeting_message', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Store Support Bot',
                'verbose_name_plural': 'Store Support Bots',
                'db_table': 'store_support_bot',
                'ordering': ['-created'],
            },
        ),
    ]
