# Generated by Django 5.0.2 on 2026-06-13 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storeapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storebot',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_bot', to='store.store'),
        ),
        migrations.AddField(
            model_name='storelogo',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='store.store'),
        ),
        migrations.AddField(
            model_name='storesupportbot',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_bot', to='store.store'),
        ),
        migrations.AlterUniqueTogether(
            name='storeapplication',
            unique_together={('store_name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='storelogo',
            unique_together={('store',)},
        ),
    ]
