# Generated by Django 5.0.2 on 2024-05-15 03:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_connected_to_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(default='9ce2c55d-70f5-449b-8b38-6b7d9a5ca2b3', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='store_description',
            field=models.TextField(default='This is store', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='store_name',
            field=models.TextField(default='DITCH Concept Store', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StoreAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_admins', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='store.store')),
            ],
            options={
                'verbose_name': 'Store Admin',
                'verbose_name_plural': 'Store Admins',
                'db_table': 'store_admin',
            },
        ),
        migrations.CreateModel(
            name='StoreBotToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('token', models.TextField(max_length=255)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_token', to='store.store')),
            ],
            options={
                'verbose_name': 'Store Bot Token',
                'verbose_name_plural': 'Store Bot Tokens',
                'db_table': 'store_bot_token',
            },
        ),
    ]
