# Generated by Django 5.0.2 on 2024-05-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_is_connected_to_telegram_store_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
