# Generated by Django 5.0.2 on 2024-05-23 03:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20240520_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='bot_username',
        ),
        migrations.CreateModel(
            name='StoreBot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bot_username', models.TextField(blank=True, max_length=100, null=True)),
                ('token', models.TextField(blank=True, max_length=255, null=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_bot', to='store.store')),
            ],
            options={
                'verbose_name': 'Store Bot',
                'verbose_name_plural': 'Store Bots',
                'db_table': 'store_bot',
            },
        ),
        migrations.CreateModel(
            name='StoreLogo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dark_logo', models.ImageField(blank=True, null=True, upload_to='store_logos')),
                ('light_logo', models.ImageField(blank=True, null=True, upload_to='store_logos')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='store.store')),
            ],
            options={
                'verbose_name': 'Store Logo',
                'verbose_name_plural': 'Store Logos',
                'db_table': 'store_logo',
                'ordering': ['-created'],
                'unique_together': {('store',)},
            },
        ),
        migrations.DeleteModel(
            name='StoreBotToken',
        ),
    ]
