# Generated by Django 5.0.2 on 2024-05-23 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_store_bot_username_storebot_storelogo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_image',
        ),
    ]
