# Generated by Django 5.0.2 on 2024-05-23 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_store_store_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storelogo',
            old_name='dark_logo',
            new_name='logo_dark',
        ),
        migrations.RenameField(
            model_name='storelogo',
            old_name='light_logo',
            new_name='logo_light',
        ),
    ]
