# Generated by Django 5.0.2 on 2024-05-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_dark_logo_storelogo_logo_dark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
