# Generated by Django 5.0.2 on 2024-05-24 05:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_store_store_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('store_name', models.TextField(max_length=100)),
                ('store_description', models.TextField(blank=True, max_length=255, null=True)),
                ('channels', models.TextField(blank=True, max_length=255, null=True)),
                ('product_category', models.TextField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Application',
                'verbose_name_plural': 'Store Applications',
                'db_table': 'store_application',
                'ordering': ['-created'],
                'unique_together': {('store_name',)},
            },
        ),
    ]
