# Generated by Django 5.0.2 on 2024-05-24 05:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_storeapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storeapplication',
            unique_together={('store_name', 'user')},
        ),
    ]
