# Generated by Django 5.0.2 on 2024-05-27 06:06
from django.conf import settings
from django.db import migrations


def create_store_logo_and_store_bot(apps, schema_editor):
    Store = apps.get_model("store", "Store")
    StoreLogo = apps.get_model("store", "StoreLogo")
    StoreBot = apps.get_model("store", "StoreBot")

    for store in Store.objects.all():
        if not hasattr(store, "logo"):
            StoreLogo.objects.create(store=store)
        if not hasattr(store, "store_bot"):
            StoreBot.objects.create(store=store)

        if store.store_url is None:
            store.store_url = f"{settings.FRONTEND_CLIENT_URL}/store/{store.id}"
            store.save()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_storeapplication_unique_together'),
    ]

    operations = [
        migrations.RunPython(create_store_logo_and_store_bot, reverse_code=migrations.RunPython.noop),
    ]
