# Generated by Django 5.0.2 on 2024-05-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20240527_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='timezone',
            field=models.TextField(default='UTC', max_length=100),
        ),
    ]
