# Generated by Django 5.0.2 on 2024-05-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_store_timezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='timezone',
            new_name='store_timezone',
        ),
    ]
