# Generated by Django 5.0.2 on 2024-06-05 10:40
from django.conf import settings
from django.db import migrations

def update_store_url(apps, schema_editor):
    Store = apps.get_model("store", "Store")

    for store in Store.objects.all():
        store.store_url = f"{settings.FRONTEND_CLIENT_URL}/en/store/{store.id}"
        store.save()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_timezone_store_store_timezone'),
    ]

    operations = [
        migrations.RunPython(update_store_url, reverse_code=migrations.RunPython.noop),
    ]
