# Generated by Django 5.0.2 on 2024-07-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20240605_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebot',
            name='telegram_store_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
