# Generated by Django 5.0.2 on 2024-07-09 06:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_storebot_telegram_store_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSupportBot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bot_username', models.CharField(blank=True, max_length=100, null=True)),
                ('bot_token', models.CharField(blank=True, max_length=255, null=True)),
                ('group_chat_id', models.IntegerField(blank=True, null=True)),
                ('message_thread_id', models.IntegerField(blank=True, null=True)),
                ('greeting_message', models.TextField(blank=True, max_length=255, null=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_bot', to='store.store')),
            ],
            options={
                'verbose_name': 'Store Support Bot',
                'verbose_name_plural': 'Store Support Bots',
                'db_table': 'store_support_bot',
                'ordering': ['-created'],
            },
        ),
    ]
