# Generated by Django 5.0.2 on 2024-07-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_storesupportbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesupportbot',
            name='group_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
