# Generated by Django 5.0.2 on 2026-06-13 12:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('PAGE_VIEWED', 'page viewed'), ('USER_REGISTERED', 'user registered'), ('USER_VISITED', 'user visited'), ('ADDED_TO_CART', 'added to cart'), ('REMOVED_FROM_CART', 'removed from cart'), ('CHECKOUT_STARTED', 'checkout started'), ('PAYMENT_STARTED', 'payment started'), ('PAYMENT_COMPLETED', 'payment completed')], max_length=20)),
                ('event_data', models.JSONField()),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-created'],
            },
        ),
    ]
