# Generated by Django 5.0.2 on 2024-05-03 05:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_remove_addedtocart_user_addedtocart_quantity_and_more'),
        ('product', '0003_auto_20240411_0926'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicecreated',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordercreated',
            name='order',
        ),
        migrations.RemoveField(
            model_name='uservisit',
            name='user',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('PAGE_VIEWED', 'page viewed'), ('USER_REGISTERED', 'user registered'), ('USER_VISITED', 'user visited'), ('ADDED_TO_CART', 'added to cart'), ('REMOVED_FROM_CART', 'removed from cart'), ('CHECKOUT_STARTED', 'checkout started'), ('PAYMENT_STARTED', 'payment started'), ('PAYMENT_COMPLETED', 'payment completed')], max_length=20)),
                ('event_data', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='AddedToCart',
        ),
        migrations.DeleteModel(
            name='InvoiceCreated',
        ),
        migrations.DeleteModel(
            name='OrderCreated',
        ),
        migrations.DeleteModel(
            name='UserVisit',
        ),
    ]
