# Generated by Django 5.0.2 on 2024-06-20 08:26

from django.db import migrations

def delete_all_carts(apps, schema_editor):
    Cart = apps.get_model("cart", "Cart")
    Cart.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_store'),
    ]

    operations = [
        migrations.RunPython(delete_all_carts)
    ]
