# Generated by Django 5.0.2 on 2024-06-20 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_store'),
        ('product', '0014_alter_wbproduct_category_alter_wbproduct_store_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_variant',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='variant',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(default='db090976-bd59-46fd-a8b7-d2a173d56ee7', on_delete=django.db.models.deletion.CASCADE, to='product.wbproductvariant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(default='23868b3d-1d91-4631-80db-a54dce5113f2', on_delete=django.db.models.deletion.CASCADE, to='product.wbproductvariantsize'),
            preserve_default=False,
        ),
    ]
