# Generated by Django 5.0.2 on 2024-06-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20240620_0826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
