# Generated by Django 5.0.2 on 2024-06-20 08:25
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20240620_0826'),
        ('product', '0014_alter_wbproduct_category_alter_wbproduct_store_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                                        primary_key=True, serialize=False,
                                        unique=True)),
                ('state', models.CharField(
                    choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'),
                             ('DELETED', 'Deleted')], default='ACTIVE',
                    max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to='cart.cart')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cart_items", to='product.wbproductvariant')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.wbproductvariantsize')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
