# Generated by Django 5.0.2 on 2024-06-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_cartitem_unique_cart_variant_and_more'),
        ('product', '0015_remove_product_store_remove_productimage_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created'], 'verbose_name': 'cart item', 'verbose_name_plural': 'cart items'},
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product_variant', 'size'), name='unique_cart_variant'),
        ),
    ]
