# Generated by Django 5.0.2 on 2024-06-20 08:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_cartitem_unique_cart_variant_and_more'),
        ('product', '0017_alter_productvariantcharacteristics_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                                        primary_key=True, serialize=False,
                                        unique=True)),
                ('state', models.CharField(
                    choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'),
                             ('DELETED', 'Deleted')], default='ACTIVE',
                    max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cart',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name="items", to='cart.cart')),
                ('product_variant',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name="cart_items",
                                   to='product.productvariant')),
                ('size',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='product.productvariantsize')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created'], 'verbose_name': 'cart item', 'verbose_name_plural': 'cart items'},
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product_variant', 'size'), name='unique_cart_variant'),
        ),
    ]
