# Generated by Django 5.0.2 on 2024-07-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_cartitem_product_variant'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_items',
        ),
    ]
