# Generated by Django 5.0.2 on 2024-04-11 09:26

from django.db import migrations


def clear_all_test_data(apps, schema_editor):
    Image = apps.get_model('core', 'Image')
    Product = apps.get_model('product', 'Product')
    ProductVariant = apps.get_model('product', 'ProductVariant')
    ProductImage = apps.get_model('product', 'ProductImage')
    Order = apps.get_model('order', 'Order')
    ShippingDetails = apps.get_model('order', 'ShippingDetails')
    Cart = apps.get_model('cart', 'Cart')
    CartItem = apps.get_model('cart', 'CartItem')
    AddedToCart = apps.get_model('analytics', 'AddedToCart')
    InvoiceCreated = apps.get_model('analytics', 'InvoiceCreated')
    OrderCreated = apps.get_model('analytics', 'OrderCreated')
    UserVisit = apps.get_model('analytics', 'UserVisit')
    User = apps.get_model('user', 'TelegramUser')
    Invoice = apps.get_model('invoice', 'Invoice')
    UserBotState = apps.get_model("telegram", "UserBotState")


    Image.objects.all().delete()
    Product.objects.all().delete()
    ProductVariant.objects.all().delete()
    ProductImage.objects.all().delete()
    Order.objects.all().delete()
    ShippingDetails.objects.all().delete()
    Cart.objects.all().delete()
    CartItem.objects.all().delete()
    AddedToCart.objects.all().delete()
    InvoiceCreated.objects.all().delete()
    OrderCreated.objects.all().delete()
    UserVisit.objects.all().delete()
    User.objects.all().delete()
    Invoice.objects.all().delete()
    UserBotState.objects.all().delete()


def generate_active_products(apps, schema_editor):
    Image = apps.get_model('core', 'Image')
    Product = apps.get_model('product', 'Product')
    ProductImage = apps.get_model('product', 'ProductImage')

    fan_wild_side_image_one = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/3fa11310-6544-4d5e-882d-af9ab5ba3689.JPG"
    )

    fan_wild_side_image_two = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/b3e0584d-fdaa-467f-bfed-d2e9f7cff8b1.JPG"
    )

    cap_wild_side_image_one = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/d31b8423-6f22-4574-924a-f72de8dedcea.JPG"
    )

    tshirt_wild_side_ditch_ymf_white_image_one = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/1579028d-ad0f-4450-998e-c1da9946a21b.JPG"
    )

    tshirt_wild_side_ditch_ymf_white_image_two = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/b0b89245-f0d0-40d2-b74a-23919d0fe4a4.JPG"
    )

    tshirt_wild_side_ditch_ymf_white_image_three = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/6e3e133a-f568-4b3f-ac9c-dce1ef7b4df2.JPG"
    )

    tshirt_wild_side_ditch_ymf_black_image_one = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/f5ae498a-1928-4668-b8f5-6b2571f00873.JPG"
    )

    tshirt_wild_side_ditch_ymf_black_image_two = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/4e0b4c69-087a-4a8e-8876-0ecdb8a1b365.JPG"
    )

    tshirt_wild_side_ditch_ymf_black_image_three = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/e74b78c3-08c2-447d-bc48-ba76c85e262d.JPG"
    )

    tshirt_wild_side_ditch_ymf_black_image_four = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/e8237601-dc0d-47fd-b1fc-fb5ddf4299fa.JPG"
    )

    tshirt_wild_side_ditch_ymf_black_image_five = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/251bfcd7-08be-4468-91e2-06aea0fae7e6.JPG"
    )

    tshirt_wild_side_ditch_ymf_black_image_six = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/606c9e68-b8d6-4e1c-a945-fdbc7dbc42d1.JPG"
    )

    tshirt_balaclava_white_image_one = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/ed9ce378-097e-4370-999c-3469481d502e.JPG"
    )

    tshirt_balaclava_black_and_white_image_one = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/2a36b4ae-ed20-4c05-b12e-016e6c1f575e.JPG"
    )

    tshirt_balaclava_white_image_three = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/b5fbc357-00f9-48ac-9f47-bf9af2bbad7e.JPG"
    )

    tshirt_balaclava_white_image_four = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/9d0aa9df-3f02-4e3c-8bce-5b017fa3ec83.JPG"
    )

    tshirt_balaclava_white_image_five = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/bfb9e3dd-8b74-4597-8632-40c521962bda.JPG"
    )
    # 1 for white, 3 for black
    tshirt_wild_side_black_and_white_image_one = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/8789d2e5-fa8e-483f-838c-e3fcd7a5e099.JPG"
    )

    tshirt_wild_side_white_image_two = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/63be9271-f784-45be-8577-8deea9375937.JPG"
    )

    tshirt_wild_side_white_image_three = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/73f00059-85aa-4670-864e-7c8cba3c3de2.JPG"
    )

    tshirt_wild_side_white_image_four = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/6203ceaa-974e-4a74-ac12-25a9b0d35df3.JPG"
    )

    tshirt_wild_side_white_image_five = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/c3cc1af8-4d55-4881-9273-d8c976489316.JPG"
    )

    fan_leopard_image_one = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/3edfdeee-d735-4e32-9ddc-81f51ebcf636.JPG"
    )

    fan_leopard_image_two = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/2d200467-4e6b-4615-a462-79f0943eba9a.JPG"
    )

    tshirt_wild_side_black_image_one = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/3a636abf-bd14-42cf-8e00-34b301d2cf25.JPG"
    )

    tshirt_wild_side_black_image_two = Image.objects.create(
        url="https://files.edgestore.dev/8yckhv8sa2g0jniq/publicFiles/_public/9c634860-0f81-4d77-bac9-ea674c7a4847.JPG"
    )

    fan_leopard = Product.objects.create(
        title="Fan Leopard",
        price=149.00,
        sku="BASE2024.FAN.01",
        quantity=10
    )

    ProductImage.objects.create(
        product=fan_leopard,
        image=fan_leopard_image_one,
        order=0
    )

    ProductImage.objects.create(
        product=fan_leopard,
        image=fan_leopard_image_two,
        order=1
    )

    tshirt_wild_side_white = Product.objects.create(
        title="T-shirt Wild Side White",
        price=169.00,
        sku="WS2024.TSHRT.03",
        quantity=10
    )

    ProductImage.objects.create(
        product=tshirt_wild_side_white,
        image=tshirt_wild_side_black_and_white_image_one,
        order=0
    )

    ProductImage.objects.create(
        product=tshirt_wild_side_white,
        image=tshirt_wild_side_black_and_white_image_one,
        order=1
    )

    ProductImage.objects.create(
        product=tshirt_wild_side_white,
        image=tshirt_wild_side_white_image_two,
        order=2
    )

    ProductImage.objects.create(
        product=tshirt_wild_side_white,
        image=tshirt_wild_side_white_image_three,
        order=3
    )

    ProductImage.objects.create(
        product=tshirt_wild_side_white,
        image=tshirt_wild_side_white_image_four,
        order=4
    )

    ProductImage.objects.create(
        product=tshirt_wild_side_white,
        image=tshirt_wild_side_white_image_five,
        order=5
    )

    tshirt_wild_side_black = Product.objects.create(
        title="T-shirt Wild Side Black",
        price=169.00,
        sku="WS2024.TSHRT.04",
        quantity=10
    )

    ProductImage.objects.create(
        product=tshirt_wild_side_black,
        image=tshirt_wild_side_black_image_one,
        order=0
    )

    ProductImage.objects.create(
        product=tshirt_wild_side_black,
        image=tshirt_wild_side_black_image_two,
        order=1
    )

    ProductImage.objects.create(
        product=tshirt_wild_side_black,
        image=tshirt_wild_side_black_and_white_image_one,
        order=2
    )

    tshirt_wild_side_ditch_ymf_white = Product.objects.create(
        title="T-shirt Wild Side DITCH x YMF White",
        price=169.00,
        sku="WS2024.TSHRT.02",
        quantity=10
    )

    ProductImage.objects.create(
        product=tshirt_wild_side_ditch_ymf_white,
        image=tshirt_wild_side_ditch_ymf_white_image_one,
        order=0
    )

    ProductImage.objects.create(
        product=tshirt_wild_side_ditch_ymf_white,
        image=tshirt_wild_side_ditch_ymf_white_image_two,
        order=2
    )

    ProductImage.objects.create(
        product=tshirt_wild_side_ditch_ymf_white,
        image=tshirt_wild_side_ditch_ymf_white_image_three,
        order=1
    )

    tshirt_wild_side_ditch_ymf_black = Product.objects.create(
        title="T-shirt Wild Side DITCH x YMF Black",
        price=169.00,
        sku="WS2024.TSHRT.01",
        quantity=10
    )

    ProductImage.objects.create(
        product=tshirt_wild_side_ditch_ymf_black,
        image=tshirt_wild_side_ditch_ymf_black_image_one,
        order=0
    )

    ProductImage.objects.create(
        product=tshirt_wild_side_ditch_ymf_black,
        image=tshirt_wild_side_ditch_ymf_black_image_two,
        order=1
    )

    ProductImage.objects.create(
        product=tshirt_wild_side_ditch_ymf_black,
        image=tshirt_wild_side_ditch_ymf_black_image_three,
        order=2
    )

    ProductImage.objects.create(
        product=tshirt_wild_side_ditch_ymf_black,
        image=tshirt_wild_side_ditch_ymf_black_image_four,
        order=3
    )

    ProductImage.objects.create(
        product=tshirt_wild_side_ditch_ymf_black,
        image=tshirt_wild_side_ditch_ymf_black_image_five,
        order=4
    )

    ProductImage.objects.create(
        product=tshirt_wild_side_ditch_ymf_black,
        image=tshirt_wild_side_ditch_ymf_black_image_six,
        order=5
    )

    fan_wild_side = Product.objects.create(
        title="Fan Wild Side",
        price=149.00,
        sku="WS2024.FAN.01",
        quantity=10
    )

    ProductImage.objects.create(
        product=fan_wild_side,
        image=fan_wild_side_image_one,
        order=0
    )

    ProductImage.objects.create(
        product=fan_wild_side,
        image=fan_wild_side_image_two,
        order=1
    )

    cap_wild_side = Product.objects.create(
        title="Cap Wild Side Black",
        price=139.00,
        sku="WS2024.CAP.02",
        quantity=10
    )

    ProductImage.objects.create(
        product=cap_wild_side,
        image=cap_wild_side_image_one,
        order=0
    )

    tshirt_balaclava_white = Product.objects.create(
        title="T-shirt Balaclava White",
        price=169.00,
        sku="BASE2024.TSHRT.02",
        quantity=10
    )

    ProductImage.objects.create(
        product=tshirt_balaclava_white,
        image=tshirt_balaclava_white_image_one,
        order=0
    )

    ProductImage.objects.create(
        product=tshirt_balaclava_white,
        image=tshirt_balaclava_black_and_white_image_one,
        order=1
    )

    ProductImage.objects.create(
        product=tshirt_balaclava_white,
        image=tshirt_balaclava_white_image_three,
        order=3
    )

    ProductImage.objects.create(
        product=tshirt_balaclava_white,
        image=tshirt_balaclava_white_image_four,
        order=4
    )

    ProductImage.objects.create(
        product=tshirt_balaclava_white,
        image=tshirt_balaclava_white_image_five,
        order=5
    )


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20240222_0527'),
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clear_all_test_data, reverse_func),
        migrations.RunPython(generate_active_products, reverse_func),
    ]
