# Generated by Django 5.0.2 on 2024-06-20 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_wbproduct_wbproductvariant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WBProductVariantCharacteristics',
        ),
    ]
