# Generated by Django 5.0.2 on 2024-06-20 03:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_characteristic_categorycharacteristic_and_more'),
        ('product', '0009_delete_wbproductvariantcharacteristics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wbproduct',
            options={'ordering': ['-created'], 'verbose_name': 'wb product', 'verbose_name_plural': 'wb products'},
        ),
        migrations.AlterModelOptions(
            name='wbproductvariant',
            options={'ordering': ['-created'], 'verbose_name': 'wb product variant', 'verbose_name_plural': 'wb product variants'},
        ),
        migrations.AlterModelOptions(
            name='wbproductvariantimage',
            options={'ordering': ['order'], 'verbose_name': 'wb product variant image', 'verbose_name_plural': 'wb product variant images'},
        ),
        migrations.AlterModelOptions(
            name='wbproductvariantsize',
            options={'ordering': ['-created'], 'verbose_name': 'wb product variant size', 'verbose_name_plural': 'wb product variant sizes'},
        ),
        migrations.AlterModelTable(
            name='wbproduct',
            table='wb_products',
        ),
        migrations.AlterModelTable(
            name='wbproductvariant',
            table='wb_product_variants',
        ),
        migrations.AlterModelTable(
            name='wbproductvariantimage',
            table='wb_product_variant_images',
        ),
        migrations.AlterModelTable(
            name='wbproductvariantsize',
            table='wb_product_variant_sizes',
        ),
        migrations.CreateModel(
            name='WBProductVariantCharacteristics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=50)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.characteristic')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariant')),
            ],
            options={
                'verbose_name': 'wb product variant characteristic',
                'verbose_name_plural': 'wb product variant characteristics',
                'db_table': 'wb_product_variant_characteristics',
                'ordering': ['-created'],
            },
        ),
    ]
