# Generated by Django 5.0.2 on 2024-06-20 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_wbproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbproductvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.wbproduct'),
        ),
        migrations.AlterField(
            model_name='wbproductvariant',
            name='wb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wbproductvariantcharacteristics',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.wbproductvariant'),
        ),
        migrations.AlterField(
            model_name='wbproductvariantimage',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.wbproductvariant'),
        ),
        migrations.AlterField(
            model_name='wbproductvariantsize',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.wbproductvariant'),
        ),
    ]
