# Generated by Django 5.0.2 on 2024-06-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_wbproductvariant_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbproductvariant',
            name='sku',
            field=models.CharField(max_length=50),
        ),
    ]
