# Generated by Django 5.0.2 on 2024-06-20 05:57

from django.db import migrations


def change_product_format(apps, schema_editor):
    Product = apps.get_model('product', 'Product')
    WBProduct = apps.get_model('product', 'WBProduct')
    Category = apps.get_model('category', "Category")
    WBProductVariant = apps.get_model('product', 'WBProductVariant')
    WBProductVariantSize = apps.get_model('product', 'WBProductVariantSize')
    WBProductVariantImage = apps.get_model('product', 'WBProductVariantImage')

    category = Category.objects.filter(name_ru="Одежда").first()

    for product in Product.objects.all():
        wb_product = WBProduct.objects.create(
            category=category,
            store=product.store
        )

        wb_product_variant = WBProductVariant.objects.create(
            product=wb_product,
            store=wb_product.store,
            name=product.title,
            short_description=product.short_description,
            description=product.description,
            brand="DITCH Concept Store",
            sku=product.sku
        )

        for product_variant in product.variants.all():
            wb_product_size = WBProductVariantSize.objects.create(
                product_variant=wb_product_variant,
                size_en=product_variant.size,
                size_ru=product_variant.size,
                price=product.price
            )

        if not product.variants.all().exists():
            wb_product_size = WBProductVariantSize.objects.create(
                product_variant=wb_product_variant,
                size_en="One Size",
                size_ru="One Size",
                price=product.price
            )

        for product_image in product.images.all():
            wb_product_image = WBProductVariantImage.objects.create(
                product_variant=wb_product_variant,
                image=product_image.image,
                order=product_image.order
            )


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_wbproductvariant_sku'),
    ]

    operations = [
        migrations.RunPython(change_product_format)
    ]
