# Generated by Django 5.0.2 on 2024-06-20 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_categorycharacteristic_category_and_more'),
        ('product', '0013_change_product_format'),
        ('store', '0015_auto_20240605_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wb_products', to='category.category'),
        ),
        migrations.AlterField(
            model_name='wbproduct',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wb_products', to='store.store'),
        ),
        migrations.AlterField(
            model_name='wbproductvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.wbproduct'),
        ),
        migrations.AlterField(
            model_name='wbproductvariant',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wb_product_variants', to='store.store'),
        ),
        migrations.AlterField(
            model_name='wbproductvariantcharacteristics',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_characteristics', to='product.wbproductvariant'),
        ),
        migrations.AlterField(
            model_name='wbproductvariantimage',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.wbproductvariant'),
        ),
        migrations.AlterField(
            model_name='wbproductvariantsize',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='product.wbproductvariant'),
        ),
    ]
