# Generated by Django 5.0.2 on 2024-06-21 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20240620_0826'),
        ('product', '0015_remove_product_store_remove_productimage_product_and_more')
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ('id', models.UUIDField(default=django.db.models.deletion.CASCADE, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="products", to="category.category")),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="products", to="store.store")),
            ],
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                ('id', models.UUIDField(default=django.db.models.deletion.CASCADE, editable=False, primary_key=True, serialize=False, unique=True)),
            ]
        )
    ]
