# Generated by Django 5.0.2 on 2024-06-21 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_wbproductvariant_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariantcharacteristics',
            options={'ordering': ['-created'], 'verbose_name': 'product variant characteristic', 'verbose_name_plural': 'product variant characteristics'},
        ),
        migrations.AlterModelTable(
            name='productvariantcharacteristics',
            table='product_variant_characteristics',
        ),
    ]
