# Generated by Django 5.0.2 on 2024-06-24 07:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_productvariantcharacteristics_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantcharacteristics',
            name='value',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
    ]
