# Generated by Django 5.0.2 on 2024-06-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_productvariantcharacteristics_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariantsize',
            options={'ordering': ['created'], 'verbose_name': 'product variant size', 'verbose_name_plural': 'product variant sizes'},
        ),
    ]
