# Generated by Django 5.0.2 on 2024-07-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_productvariantsize_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['order_display'], 'verbose_name': 'product variant', 'verbose_name_plural': 'product variants'},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='order_display',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
