# Generated by Django 5.0.2 on 2024-07-03 04:52

from django.db import migrations


def set_product_variant_order(apps, schema_editor):
    ProductVariant = apps.get_model('product', 'ProductVariant')

    for idx, product_variant in enumerate(ProductVariant.objects.all().order_by('created')):
        product_variant.display_order = idx
        product_variant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.RunPython(set_product_variant_order),
    ]
