# Generated by Django 5.0.2 on 2024-07-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20240703_0452'),
        ('store', '0018_alter_storesupportbot_group_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariantsize',
            name='wb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['wb_id'], name='product_var_wb_id_7a14b4_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariantsize',
            index=models.Index(fields=['wb_id'], name='product_var_wb_id_29391d_idx'),
        ),
    ]
