# Generated by Django 5.0.2 on 2026-06-13 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipping', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='store_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.storeuser'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='contact_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_label', to='shipping.contactinformation'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='store_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.storeuser'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_label', to='shipping.shippingaddress'),
        ),
    ]
