# Generated by Django 5.0.2 on 2024-04-22 05:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_remove_order_shipping_details_and_more'),
        ('shipping', '0002_shippingdetails_carrier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingdetails',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='shippingdetails',
            name='shipping_amount',
        ),
        migrations.RemoveField(
            model_name='shippingdetails',
            name='tracking_number',
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('carrier', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_label', to='shipping.shippingdetails')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='order.order')),
            ],
            options={
                'verbose_name': 'shipping',
                'verbose_name_plural': 'shipping',
                'db_table': 'shipping',
                'ordering': ['-created'],
            },
        ),
    ]
