# Generated by Django 5.0.2 on 2024-04-24 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_remove_shippingdetails_carrier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='order',
        ),
    ]
