# Generated by Django 5.0.2 on 2024-06-14 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_contactinformation_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='details',
        ),
        migrations.AddField(
            model_name='shipping',
            name='contact_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_label', to='shipping.contactinformation'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_label', to='shipping.shippingaddress'),
        ),
    ]
