# Generated by Django 5.0.2 on 2024-06-20 02:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50)),
                ('name_ru', models.CharField(max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('STRING', 'STRING'), ('NUMBER', 'NUMBER'), ('BOOLEAN', 'BOOLEAN'), ('ARRAY_STRING', 'ARRAY_STRING'), ('ARRAY_NUMBER', 'ARRAY_NUMBER')], max_length=50)),
                ('max_count', models.IntegerField(default=1)),
                ('unit_name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_name_ru', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('wb_id', models.IntegerField()),
                ('name_en', models.CharField(max_length=50)),
                ('name_ru', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.characteristic')),
            ],
        ),
        migrations.CreateModel(
            name='CharacteristicsChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('value_en', models.CharField(max_length=50)),
                ('value_ru', models.CharField(max_length=50)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='category.characteristic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
