# Generated by Django 5.0.2 on 2026-06-13 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('wb_id', models.IntegerField()),
                ('required', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('STRING', 'STRING'), ('NUMBER', 'NUMBER'), ('BOOLEAN', 'BOOLEAN'), ('ARRAY_STRING', 'ARRAY_STRING'), ('ARRAY_NUMBER', 'ARRAY_NUMBER')], max_length=50)),
                ('max_count', models.IntegerField(default=1)),
                ('unit_name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_name_ru', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'characteristic',
                'verbose_name_plural': 'characteristics',
                'db_table': 'characteristics',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('wb_id', models.IntegerField()),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='category.category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CharacteristicsChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('value_en', models.CharField(max_length=100)),
                ('value_ru', models.CharField(max_length=100)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='category.characteristic')),
            ],
            options={
                'verbose_name': 'characteristic choice',
                'verbose_name_plural': 'characteristic choices',
                'db_table': 'characteristics_choices',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CategoryCharacteristic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='category.category')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='category.characteristic')),
            ],
            options={
                'verbose_name': 'category characteristic',
                'verbose_name_plural': 'category characteristics',
                'db_table': 'category_characteristics',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['category'], name='category_ch_categor_4dd900_idx')],
            },
        ),
    ]
