# Generated by Django 5.0.2 on 2024-06-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('product', '0009_delete_wbproductvariantcharacteristics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristicschoice',
            name='characteristic',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.DeleteModel(
            name='CategoryCharacteristic',
        ),
        migrations.DeleteModel(
            name='Characteristic',
        ),
        migrations.DeleteModel(
            name='CharacteristicsChoice',
        ),
    ]
