# Generated by Django 5.0.2 on 2024-06-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='wb_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
