# Generated by Django 5.0.2 on 2024-06-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_characteristic_wb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='name_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
