# Generated by Django 5.0.2 on 2024-06-20 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_alter_characteristic_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycharacteristic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='category.category'),
        ),
        migrations.AlterField(
            model_name='categorycharacteristic',
            name='characteristic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='category.characteristic'),
        ),
    ]
