# Generated by Django 5.0.2 on 2024-06-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_categorycharacteristic_category_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='categorycharacteristic',
            index=models.Index(fields=['category'], name='category_ch_categor_4dd900_idx'),
        ),
    ]
