# Generated by Django 5.0.2 on 2024-06-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_categorycharacteristic_category_ch_categor_4dd900_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristicschoice',
            name='value_en',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='characteristicschoice',
            name='value_ru',
            field=models.CharField(max_length=100),
        ),
    ]
