# Generated by Django 5.0.2 on 2024-06-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_alter_characteristicschoice_value_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
