# Generated by Django 5.0.2 on 2024-07-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_alter_characteristic_name_en_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['wb_id'], name='categories_wb_id_a2479e_idx'),
        ),
        migrations.AddIndex(
            model_name='characteristic',
            index=models.Index(fields=['wb_id'], name='characteris_wb_id_fbf759_idx'),
        ),
    ]
