# Generated by Django 5.0.2 on 2024-07-08 10:24

import django.contrib.postgres.fields
import django.db.models.deletion
import marketing.models.marketing
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0016_storebot_telegram_store_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualMailing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('audience', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ALL', 'ALL'), ('NEW', 'NEW'), ('ADDED_TO_CART', 'ADDED_TO_CART'), ('STARTED_CHECKOUT', 'STARTED_CHECKOUT'), ('PURCHASED', 'PURCHASED')], max_length=50), blank=True, default=marketing.models.marketing.default_audience, size=None)),
                ('cta_text', models.CharField(max_length=50)),
                ('cta_url', models.URLField(max_length=255)),
                ('user_count', models.IntegerField(default=0)),
                ('successful_send_count', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='store.store')),
            ],
            options={
                'verbose_name': 'Manual Mailing',
                'verbose_name_plural': 'Manual Mailings',
                'db_table': 'manual_mailings',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ManualMailingFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('send_as_file', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='manual_mailing_files')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='marketing.manualmailing')),
            ],
            options={
                'verbose_name': 'Manual Mailing File',
                'verbose_name_plural': 'Manual Mailing Files',
                'db_table': 'manual_mailing_files',
                'ordering': ['-created'],
            },
        ),
    ]
