# Generated by Django 5.0.2 on 2024-07-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualmailing',
            name='cta_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manualmailing',
            name='cta_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
