# Generated by Django 5.0.2 on 2024-07-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_manualmailing_cta_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualmailing',
            name='status',
            field=models.CharField(choices=[('SENT', 'SENT'), ('DRAFT', 'DRAFT')], default='DRAFT', max_length=50),
        ),
    ]
