# Generated by Django 5.0.2 on 2024-03-08 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
        ('order', '0006_remove_order_payment_status_order_delivery_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='order.order'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('PAID', 'paid'), ('CANCELLED', 'cancelled'), ('EXPIRED', 'expired')], default='ACTIVE', max_length=50),
        ),
    ]
