# Generated by Django 5.0.2 on 2024-04-28 06:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0002_alter_invoice_order_alter_invoice_payment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
