# Generated by Django 5.0.2 on 2026-06-13 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('JOIN_PROMO_CODE', 'JOIN_PROMO_CODE'), ('SHOPPING', 'SHOPPING')], default='JOIN_PROMO_CODE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bot_states', to='store.store')),
            ],
            options={
                'verbose_name': 'User Bot State',
                'verbose_name_plural': 'User Bot States',
                'db_table': 'user_bot_state',
            },
        ),
    ]
