# Generated by Django 5.0.2 on 2024-03-10 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('JOIN_PROMO_CODE', 'JOIN_PROMO_CODE'), ('SHOPPING', 'SHOPPING')], default='JOIN_PROMO_CODE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Bot State',
                'verbose_name_plural': 'User Bot States',
                'db_table': 'user_bot_state',
                'unique_together': {('user', 'state')},
            },
        ),
    ]
