# Generated by Django 5.0.2 on 2024-05-20 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_store_owner_store_bot_username_and_more'),
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbotstate',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bot_states', to='store.store'),
        ),
    ]
