# Generated by Django 5.0.2 on 2024-05-20 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20240520_0731'),
        ('telegram', '0002_userbotstate_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbotstate',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bot_states', to='store.store'),
        ),
    ]
