# Generated by Django 5.0.2 on 2024-05-29 05:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20240527_0606'),
        ('telegram', '0003_alter_userbotstate_store'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbotstate',
            unique_together={('user', 'state', 'store')},
        ),
    ]
