# Generated by Django 5.0.2 on 2024-04-25 08:02

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('order', '0019_auto_20240424_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                                        primary_key=True, serialize=False,
                                        unique=True)),
                ('state', models.CharField(
                    choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'),
                             ('DELETED', 'Deleted')], default='ACTIVE',
                    max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=50)),
                ('other_info', models.JSONField()),
            ],
            options={
                'verbose_name': 'payment method',
                'verbose_name_plural': 'payment methods',
                'db_table': 'payment_methods',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                                        primary_key=True, serialize=False,
                                        unique=True)),
                ('state', models.CharField(
                    choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'),
                             ('DELETED', 'Deleted')], default='ACTIVE',
                    max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('payment_status', models.CharField(max_length=50)),
                ('subtotal_amount',
                 models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_amount',
                 models.DecimalField(decimal_places=2, default=Decimal('0.00'),
                                     max_digits=10)),
                ('total_amount',
                 models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(
                    choices=[('RUB', 'RUB'), ('AED', 'AED'), ('USD', 'USD'),
                             ('IDR', 'IDR'), ('USDT', 'USDT')], default='USD',
                    max_length=4)),
                ('transaction_id', models.CharField(max_length=50)),
                ('payment_date', models.DateTimeField()),
                ('payment_expiry', models.DateTimeField()),
                ('additional_info', models.JSONField()),
                ('order',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='payments', to='order.order')),
                ('payment_method', models.ForeignKey(blank=True, null=True,
                                                     on_delete=django.db.models.deletion.SET_NULL,
                                                     related_name='payments',
                                                     to='payment.paymentmethods')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'db_table': 'payment',
                'ordering': ['-created'],
            },
        ),
    ]
