# Generated by Django 5.0.2 on 2026-06-13 12:26

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'unpaid'), ('PAID', 'paid'), ('REFUNDED', 'refunded'), ('EXPIRED', 'expired')], default='UNPAID', max_length=50)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('AED', 'AED'), ('USD', 'USD'), ('IDR', 'IDR'), ('USDT', 'USDT')], default='USD', max_length=4)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_expiry', models.DateTimeField(blank=True, null=True)),
                ('additional_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'db_table': 'payment',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('provider', models.CharField(choices=[('WALLET_PAY', 'WALLET_PAY'), ('TELEGRAM_INVOICE', 'TELEGRAM_INVOICE'), ('BANK_TRANSFER', 'BANK_TRANSFER'), ('CRYPTO_TRANSFER', 'CRYPTO_TRANSFER')], max_length=25)),
                ('other_info', models.JSONField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'payment method',
                'verbose_name_plural': 'payment methods',
                'db_table': 'payment_method',
                'ordering': ['-created'],
            },
        ),
    ]
