# Generated by Django 5.0.2 on 2024-04-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentMethods',
            new_name='PaymentMethod',
        ),
        migrations.AlterModelTable(
            name='paymentmethod',
            table='payment_method',
        ),
    ]
