# Generated by Django 5.0.2 on 2024-04-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_paymentmethods_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('PAID', 'paid'), ('REFUNDED', 'refunded'), ('EXPIRED', 'expired')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='other_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='provider',
            field=models.CharField(choices=[('WALLET_PAY', 'WALLET_PAY'), ('TELEGRAM_INVOICE', 'TELEGRAM_INVOICE'), ('BANK_TRANSFER', 'BANK_TRANSFER'), ('CRYPTO_TRANSFER', 'CRYPTO_TRANSFER')], max_length=25),
        ),
    ]
