# Generated by Django 5.0.2 on 2024-04-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='additional_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
