# Generated by Django 5.0.2 on 2024-04-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'unpaid'), ('PAID', 'paid'), ('REFUNDED', 'refunded'), ('EXPIRED', 'expired')], default='UNPAID', max_length=50),
        ),
    ]
