# Generated by Django 5.0.2 on 2024-04-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='payment_gateway',
            field=models.CharField(default='Stripe', max_length=50),
            preserve_default=False,
        ),
    ]
