# Generated by Django 5.0.2 on 2024-04-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_paymentmethod_payment_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
