# Generated by Django 5.0.2 on 2024-05-01 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_paymentmethod_button_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='payment_gateway',
        ),
    ]
