# Generated by Django 5.0.2 on 2024-05-20 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_paymentmethod_store'),
        ('store', '0005_auto_20240520_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='store.store'),
        ),
    ]
