# Generated by Django 5.0.2 on 2024-06-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_alter_paymentmethod_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
    ]
