"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, True))

env_file = os.path.join(BASE_DIR, ".env")

# Local development loads configuration from a .env file when present. In
# deployment (e.g. Railway), configuration is injected directly into the
# process environment, which django-environ reads automatically — no .env
# file or external secret manager is required.
if os.path.isfile(env_file):
    print("Loading configuration from local .env file")
    env.read_env(env_file)
else:
    print("No .env file found; loading configuration from the environment")

DEBUG = env("DEBUG")
SECRET_KEY = env("SECRET_KEY")

SERVICE_URL = env("SERVICE_URL", default=None)
FRONTEND_CLIENT_URL = env("FRONTEND_CLIENT_URL", default=None)
ADMIN_CLIENT_URL = env("ADMIN_CLIENT_URL", default=None)

CORS_ALLOWED_ORIGINS = [
    "https://studio.apollographql.com"
]

CSRF_TRUSTED_ORIGINS = [
    "https://studio.apollographql.com"
]

# Public host of this backend. Railway injects RAILWAY_PUBLIC_DOMAIN
# automatically; SERVICE_URL may also be set explicitly to the public URL.
RAILWAY_PUBLIC_DOMAIN = env("RAILWAY_PUBLIC_DOMAIN", default=None)

ALLOWED_HOSTS = []
if RAILWAY_PUBLIC_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)
    CSRF_TRUSTED_ORIGINS.append(f"https://{RAILWAY_PUBLIC_DOMAIN}")
if SERVICE_URL:
    ALLOWED_HOSTS.append(urlparse(SERVICE_URL).netloc)
    CSRF_TRUSTED_ORIGINS.append(SERVICE_URL)

if not ALLOWED_HOSTS:
    # No public host configured (e.g. local development) — allow all.
    ALLOWED_HOSTS = ["*"]

if DEBUG:
    SECURE_SSL_REDIRECT = False
    SECURE_PROXY_SSL_HEADER = None
else:
    # Railway terminates TLS at its proxy and forwards the original scheme.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True

CACHE_MIDDLEWARE_SECONDS = 0

#
if FRONTEND_CLIENT_URL:
    CSRF_TRUSTED_ORIGINS.append(FRONTEND_CLIENT_URL)
    CORS_ALLOWED_ORIGINS.append(FRONTEND_CLIENT_URL)

    CSRF_TRUSTED_ORIGINS.append(ADMIN_CLIENT_URL)
    CORS_ALLOWED_ORIGINS.append(ADMIN_CLIENT_URL)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

APPEND_SLASH = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'graphene_django',
    'corsheaders',
    'core.apps.CoreConfig',
    'product.apps.ProductConfig',
    'cart.apps.CartConfig',
    'order.apps.OrderConfig',
    'user.apps.UserConfig',
    'analytics.apps.AnalyticsConfig',
    'invoice.apps.InvoiceConfig',
    'telegram.apps.TelegramConfig',
    'shipping.apps.ShippingConfig',
    'payment.apps.PaymentConfig',
    'authentication.apps.AuthenticationConfig',
    'store.apps.StoreConfig',
    'category.apps.CategoryConfig',
    'marketing.apps.MarketingConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.GraphqlErrorLogMiddleware',
    'core.middleware.AuthMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shop.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': env.db()
}

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Static files are served by WhiteNoise from STATIC_ROOT (populated by
# `collectstatic` at container start). Product images are uploaded to
# EdgeStore from the frontend and stored as URLs, so they don't use Django
# storage. The few model FileFields fall back to the local filesystem.
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'user.TelegramUser'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.authentication.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.authentication.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.authentication.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.authentication.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

GRAPHENE = {
    "SCHEMA": "core.gql.schema",
}

CORS_ALLOW_CREDENTIALS = True

LOGGING = {
    'version': 1,
    'formatters': {
        'detailed': {
            'format': '[%(asctime)s] %(levelname)s in %(module)s.%(funcName)s: %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {},
    'loggers': {
        '': {
            'handlers': [],
            'level': 'DEBUG',
            'propagate': True,
        }
    }
}

# Log to stdout in every environment. The platform (Railway) captures the
# container's stdout, so no cloud-specific logging client is needed.
LOGGING['handlers']['console'] = {
    'level': 'DEBUG',
    'class': 'logging.StreamHandler',
    'formatter': 'detailed',
}
LOGGING['loggers']['']['handlers'].append('console')

# ------------------- TELEGRAM -------------------
TELEGRAM_API_URL = env("TELEGRAM_API_URL")
TELEGRAM_SHOP_BOT_USERNAME = env("TELEGRAM_SHOP_BOT_USERNAME")
TELEGRAM_SUPPORT_BOT_USERNAME = env("TELEGRAM_SUPPORT_BOT_USERNAME")
TELEGRAM_SHOP_TOKEN = env("TELEGRAM_SHOP_TOKEN")
TELEGRAM_SUPPORT_TOKEN = env("TELEGRAM_SUPPORT_TOKEN")
TELEGRAM_WEB_APP_URL = env("TELEGRAM_WEB_APP_URL")
TELEGRAM_ADMIN_CHAT_ID = env("TELEGRAM_ADMIN_CHAT_ID")
TELEGRAM_SUPPORT_CHAT_ID = env("TELEGRAM_SUPPORT_CHAT_ID")

SUPERUSER_TELEGRAM_ID = env("SUPERUSER_TELEGRAM_ID")
TELEGRAM_ADMIN_BOT_TOKEN = env("TELEGRAM_ADMIN_BOT_TOKEN")

# PAYMENT
# Wallet Pay credentials are stored encrypted per-store in the database
# (PaymentMethod.other_info), not in the environment. Only the return URL the
# customer comes back to after paying is configured here.
TELEGRAM_PAYMENT_RETURN_URL = env("TELEGRAM_PAYMENT_RETURN_URL")

# ------------------- ENCRYPTION -------------------
AES_SECRET_KEY = env("AES_SECRET_KEY")
AES_IV = env("AES_IV")

JWT_SECRET_KEY = env("JWT_SECRET_KEY")
