name: Run API Tests

on:
  pull_request:
    paths:
      - 'api-shop/**'
      - '.github/workflows/api_run_test.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run API Tests
    environment: Staging

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        cd api-shop/shop
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django tests
      run: |
        cd api-shop/shop
        python manage.py test
      env:
        SETTINGS_NAME: ${{ secrets.SETTINGS_NAME }}

