name: Build and Deploy to Google Cloud Run

on:
  release:
    types: [created]

env:
  PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
  SERVICE_NAME: ditch/api-shop # Change to your Cloud Run service name
  IMAGE: gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT }}/ditch-api # Change to your image name
  REGION: asia-southeast1 # Change to your Google Cloud region

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_CLOUD_SA_KEY }}
        export_default_credentials: true

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ${{ env.IMAGE }}:${{ github.event.release.tag_name }}
          ${{ env.IMAGE }}:latest
        build-args: |
          PROJECT_ID=${{ secrets.GOOGLE_CLOUD_PROJECT }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image $IMAGE:${{ github.event.release.tag_name }} \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated

