name: Build and Deploy Admin Client to Google Cloud Run to Staging

on:
  pull_request:
    branches:
      - main
    paths:
      - "apps/admin-shop/**"
      - ".github/workflows/build_and_deploy_staging_admin.yml"
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
  GOOGLE_CLOUD_SA_KEY: ${{ secrets.GOOGLE_CLOUD_SA_KEY }}
  SERVICE_NAME: ditch-admin-stage # Change to your service name
  IMAGE: asia-southeast1-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/ditch/ditch-admin # Change to your image name
  REGION: asia-southeast1 # Change to your Google Cloud region

jobs:
  setup-build-and-deploy-admin-frontend:
    environment: Staging
    name: Setup, Build, Publish and Deploy Admin Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 6

      - run: echo $SHA
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: asia-southeast1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_CLOUD_SA_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./apps/admin-shop/Dockerfile
          context: ./
          tags: |
            ${{ env.IMAGE }}:${{ env.SHA }}
            ${{ env.IMAGE }}:latest
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.BACKEND_SERVICE_URL }}
            EDGE_STORE_ACCESS_KEY=${{ secrets.EDGE_STORE_ACCESS_KEY }}
            EDGE_STORE_SECRET_KEY=${{ secrets.EDGE_STORE_SECRET_KEY }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            NEXT_PUBLIC_BOT_USERNAME=${{ secrets.BOT_USERNAME }}


      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --quiet \
            --image ${{ env.IMAGE }}:latest \
            --region ${{ env.REGION }} \
            --platform managed \
            --format json \
            --allow-unauthenticated \
            --service-account ${{ secrets.GOOGLE_CLOUD_SA_EMAIL }}


