name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
  GOOGLE_CLOUD_SA_KEY: ${{ secrets.GOOGLE_CLOUD_SA_KEY }}
  SERVICE_NAME: api-shop # Change to your Cloud Run service name
  IMAGE: asia-southeast1-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/ditch/ditch-api # Change to your image name
  REGION: asia-southeast1 # Change to your Google Cloud region

jobs:
  setup-build-publish-deploy:
    environment: deployment
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_CLOUD_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GAR
      uses: docker/login-action@v3
      with:
        registry: asia-southeast1-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GOOGLE_CLOUD_SA_KEY }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        context: ./api-shop/shop
        tags: | 
          ditch/ditch-api:latest
          ditch/ditch-api:${{ github.short_sha }}
          $IMAGE:${{ github.short_sha }}
          $IMAGE:latest
        

    - id: Deploy
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: $SERVICE_NAME
        image: $IMAGE:latest

