name: Build and Deploy API to Google Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - "api-shop/**"
      - ".github/workflows/build_and_deploy_prod_api.yml"
  workflow_dispatch:


env:
  PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
  GOOGLE_CLOUD_SA_KEY: ${{ secrets.GOOGLE_CLOUD_SA_KEY }}
  SERVICE_NAME: ditch-api # Change to your Cloud Run service name
  IMAGE: asia-southeast1-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/ditch/ditch-api # Change to your image name
  REGION: asia-southeast1 # Change to your Google Cloud region

jobs:
  setup-build-publish-deploy-backend:
    environment: deployment
    name: Setup, Build, Publish and Deploy Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_CLOUD_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --quiet \
          --image ${{ env.IMAGE }}:latest \
          --region ${{ env.REGION }} \
          --platform managed \
          --format json \
          --allow-unauthenticated \
          --service-account ${{ secrets.GOOGLE_CLOUD_SA_EMAIL }}
