name: Lint Shop
on:
  pull_request:
    branches:
      - main
    paths:
      - "apps/tg-shop/**"
      - ".github/workflows/lint_shop.yml"

jobs:
  run-lint-shop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint:tg
